version: '3'
services:
  run:
    build: .
    environment:
      - DEBUG=false
      - SHELL=/bin/bash
      - PG_HOST=pgbouncer
      - PG_PORT=5432
      - PG_DB=datareaderxmlchile
      - PG_USER=datareaderxmlchile
      - PG_PASSWORD=datareaderxmlchile
      - COMMAND=init 
      - JUPYTER_TOKEN=the5ooxoo0ahNoojuNgiahoon8koozie
      - CREATE=true # This variable is only necessary for local development
    depends_on:
      - db
    ports:
      - "1022:22"
      - "3002:3002" # Debugpy if Debug=true | Matching the .vscode launch "debugServer": 3002 
      - "8888:8888"
    tty: true
    volumes:
      - ./:/code
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=datareaderxmlchile
      - POSTGRES_USER=datareaderxmlchile
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  pgbouncer:
    image: edoburu/pgbouncer:1.17.0
    environment:
      - DB_HOST=db
      - DB_PASSWORD=datareaderxmlchile
      - DB_USER=datareaderxmlchile
      - POOL_MODE=transaction
      - SERVER_RESET_QUERY=DISCARD ALL
      - AUTH_TYPE=plain
    restart: always
  pgadmin:
    image: dpage/pgadmin4:6.15
    entrypoint: >
      /bin/sh -c "
      chmod 600 /pgadmin4/pgpass;
      chown pgadmin:pgadmin /pgadmin4/pgpass;
      cp -afr /pgadmin4/pgpass /var/lib/pgadmin/;
      /entrypoint.sh
      "
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@c3xsrv.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8098:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json 
      - ./pgadmin/pgpass:/pgadmin4/pgpass
volumes:
  db-data:
  pgadmin-data:
