"""initial

Revision ID: d98b89172244
Revises:
Create Date: 2023-01-04 10:23:46.317709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d98b89172244"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usuarios")
    # ### end Alembic commands ###
